import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Homepage from '../components/Homepage'
import About from '../components/About'
import Experience from '../components/Experience'
import Skills from '../components/Skills'

export default function Home() {
  return (
    <div className='bg-[rgb(30,30,30)] text-white snap-y span-mandatory oveflow-scroll z-0'>
      <Head>
        <title>Frezz1cks portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://media.discordapp.net/attachments/1014234466434175102/1051907064257060984/F_2.png?width=553&height=671" />
      </Head>
      
      <Header/>
      <section id='hero' className='snap-center'>
        <Homepage/>
      </section>
      <section id='about' className='snap-center'>
        <About/>
      </section>
      <section id='experience' className='snap-center'>
          <Experience/>
      </section>
      <section id='skills' className='snap-start'>
        <Skills/>
      </section>
    </div>
  )
}
